'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace Interzoic.LMS.CommonControls

    Partial Public Class DateRangeSelector

        '''<summary>
        '''pnlDateRange control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlDateRange As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''tblDateRange control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents tblDateRange As Global.System.Web.UI.HtmlControls.HtmlTable

        '''<summary>
        '''trDateRange control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents trDateRange As Global.System.Web.UI.HtmlControls.HtmlTableRow

        '''<summary>
        '''tdDrpDownDateRange control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents tdDrpDownDateRange As Global.System.Web.UI.HtmlControls.HtmlTableCell

        '''<summary>
        '''cmbDateRange control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmbDateRange As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''TrStartDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents TrStartDate As Global.System.Web.UI.HtmlControls.HtmlTableRow

        '''<summary>
        '''tdStartDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents tdStartDate As Global.System.Web.UI.HtmlControls.HtmlTableCell

        '''<summary>
        '''lblStartDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblStartDate As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''tdTextboxStartDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents tdTextboxStartDate As Global.System.Web.UI.HtmlControls.HtmlTableCell

        '''<summary>
        '''rdpStartDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rdpStartDate As Global.Telerik.Web.UI.RadDatePicker

        '''<summary>
        '''valEffectiveDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents valEffectiveDate As Global.System.Web.UI.WebControls.CustomValidator

        '''<summary>
        '''TrEndDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents TrEndDate As Global.System.Web.UI.HtmlControls.HtmlTableRow

        '''<summary>
        '''tdEndDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents tdEndDate As Global.System.Web.UI.HtmlControls.HtmlTableCell

        '''<summary>
        '''lblEndDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblEndDate As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''tdTextboxEndDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents tdTextboxEndDate As Global.System.Web.UI.HtmlControls.HtmlTableCell

        '''<summary>
        '''rdpEndDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rdpEndDate As Global.Telerik.Web.UI.RadDatePicker

        '''<summary>
        '''CustomValidator1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents CustomValidator1 As Global.System.Web.UI.WebControls.CustomValidator

        '''<summary>
        '''tblRangeValidator control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents tblRangeValidator As Global.System.Web.UI.HtmlControls.HtmlTableRow

        '''<summary>
        '''valDateRange control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents valDateRange As Global.System.Web.UI.WebControls.CompareValidator

        '''<summary>
        '''TrInterval control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents TrInterval As Global.System.Web.UI.HtmlControls.HtmlTableRow

        '''<summary>
        '''tdRBLInterval control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents tdRBLInterval As Global.System.Web.UI.HtmlControls.HtmlTableCell

        '''<summary>
        '''lblInterval control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblInterval As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''tdRBLIntervalCtl control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents tdRBLIntervalCtl As Global.System.Web.UI.HtmlControls.HtmlTableCell

        '''<summary>
        '''RBLInterval control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents RBLInterval As Global.System.Web.UI.WebControls.RadioButtonList
    End Class
End Namespace
